### PR TITLE
Upgrade app to 3.20 

### PR DESCRIPTION
**Pull request by aatauil**

### CODE REVIEW

**Comment by HugaertsDries** [comment]
@aatauil Noticed a deprecation when running the branch. Seems it was not happy with how `ember-basic-dropdown:^2.0.0` was handeling something. Bumping it to `3.0.0` seems to have done the trick. But is there any reason you didn’t do this? Maybe I’m being a little to optimistic.

**Comment by HugaertsDries** [comment]
I also notice allot of `Async Request leaks detected` warnings. I think this is coming from [here](https://github.com/lblod/frontend-leidinggevenden-databank/blob/d33b01abf8cefcbf4aa43f5ea68fa1212bbb9adc/app/adapters/application.js#L3):

```
WARNING: Async Request leaks detected. Add a breakpoint here and set `store.generateStackTracesForTrackedRequests = true;`to inspect traces for leak origins:
         - DS: Handle Adapter#findBelongsTo of bestuursorgaan : bestuurseenheid
         - DS: Handle Adapter#findBelongsTo of bestuursorgaan : bestuurseenheid
         - DS: Handle Adapter#findBelongsTo of functionaris : bestuursfunctie
         - DS: Handle Adapter#findBelongsTo of functionaris : bestuursfunctie
         - DS: Handle Adapter#findBelongsTo of functionaris : bestuursfunctie
         - DS: Handle Adapter#findBelongsTo of functionaris : bestuursfunctie
         - DS: Handle Adapter#findBelongsTo of functionaris : persoon
         - DS: Handle Adapter#findBelongsTo of functionaris : persoon
         - DS: Handle Adapter#findBelongsTo of functionaris : functionaris-status-code

**Comment by HugaertsDries** [comment]
Deprecation for `Attempted to call store.adapterFor()`. Not yet been able to isolate where it is coming from nor reproduce it:

```
DEPRECATION: Attempted to call store.adapterFor(), but the store instance has already been destroyed. [deprecation id: ember-data:method-calls-on-destroyed-store]
        at logDeprecationStackTrace (/tmp/broccoli-1016783QY2t5rH8J8mC/out-574-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:106:1)
        at HANDLERS.<computed> (/tmp/broccoli-1016783QY2t5rH8J8mC/out-574-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:26:1)
        at raiseOnDeprecation (/tmp/broccoli-1016783QY2t5rH8J8mC/out-574-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:133:1)
        at HANDLERS.<computed> (/tmp/broccoli-1016783QY2t5rH8J8mC/out-574-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:26:1)
        at invoke (/tmp/broccoli-1016783QY2t5rH8J8mC/out-574-append_ember_auto_import_analyzer/assets/@ember/debug/lib/handlers.js:38:1)
        at Object.deprecate (/tmp/broccoli-1016783QY2t5rH8J8mC/out-574-append_ember_auto_import_analyzer/assets/@ember/debug/lib/deprecate.js:171:1)
        at assertDestroyedStore (/tmp/broccoli-1016783QY2t5rH8J8mC/out-574-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:9761:1)
        at Store.adapterFor (/tmp/broccoli-1016783QY2t5rH8J8mC/out-574-append_ember_auto_import_analyzer/assets/addon-tree-output/@ember-data/store/-private.js:9360:1)
 ...

**Comment by HugaertsDries** [comment]
Aside from these warnings the frontend seems to work as expected. @cecemel do these warnings/deprecations need to be fixed to merge?

**Comment by aatauil** [comment]
> @aatauil Noticed a deprecation when running the branch. Seems it was not happy with how `ember-basic-dropdown:^2.0.0` was handeling something. Bumping it to `3.0.0` seems to have done the trick. But is there any reason you didn’t do this? Maybe I’m being a little to optimistic.

Currently trying to reproduce but I dont get the warning for some reason. I deleted node_modules and ran npm install but still no warning. Can you post the steps to reproduce?

**Comment by HugaertsDries** [comment]
> Currently trying to reproduce but I dont get the warning for some reason. I deleted node_modules and ran npm install but still no warning. Can you post the steps to reproduce?

Node version `v12.14.1` *also tried latest* `v14.15.4`
NPM version `6.14.4`

Steps to re-produce:

1) remove the node_modules `rm -rf node_modules/`
2) run `npm install`
3) run `ember serve --proxy=http://the-back-end`

Deprecation warning:
```shell
DEPRECATION: The use of the private `{{-in-element}}` is deprecated, please refactor to the public `{{in-element}}`. ('ember-basic-dropdown/templates/components/basic-dropdown-content.hbs' @ L1:C0)  [deprecation id: glimmer.private-in-element]
        at logDeprecationStackTrace (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:1930:21)
        at HANDLERS.<computed> (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:2027:9)
        at raiseOnDeprecation (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:1957:9)
        at HANDLERS.<computed> (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:2027:9)
        at invoke (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:2039:9)
        at deprecate (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:1995:28)
        at BlockStatement (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:10730:59)
        at visitNode (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:7742:16)
        at visitArray (/home/dries/Projects/LBLOD/frontend-leidinggevenden-databank/node_modules/ember-source/dist/ember-template-compiler.js:7833:20)
 ```
@aatauil

**Comment by aatauil** [comment]
I managed  to reproduce the issue after re-cloning the repo and updated ember-basic-dropdown to the latest one. I talked to Felix and the `Async Request leaks` can be ignored if it is indeed coming from the applicationAdapter. ( didnt really manage to reproduce consistently

**Comment by aatauil** [comment]
Still testing the app and no other deprecation or errors appear for me then already known ones.

- The ` OutgoingMessage.prototype._headers is deprecated` is a node version http-server version issue but I dont see a solution to that immediately as it has to get fixed by fastboot.  
 - Async Request Leaks can be ignored until we known if we need to refactor or can remove the ApplicationAdapter as it is an old workaround that might be already fixed in the backend
 - `Attempted to call store.adapterFor()` unable to reproduce
 
 Since these warnings dont cause problems to the app or appear in the developer console I think they can be ignored and the changes can be merged

**Pull request merged**
